AppBundle\Entity\Tweet:
  type: entity
  repositoryClass: AppBundle\Repository\TweetRepository
  table: tweets
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    data:
      type: string
    created:
      type: datetime
  manyToOne:
    location:
      targetEntity: Location
      inversedBy: tweets
      joinColumn:
        name: location_id
        referenceColumnName: id